export interface StaticProductItem {
  id: string;
  name: string;
  slug: string;
  sku: string;
  price: number;
  compare_at_price: number;
  cost_price: number;
  description: string;
  short_description: string;
  stock_quantity: number;
  is_featured: boolean;
  status: string;
  category: { name: string; slug: string };
  brand: { name: string; slug: string };
  images: { url: string; is_primary: boolean }[];
  specifications: { key: string; value: string }[];
}

export const INNOVATION_LAB_65_PRODUCTS: StaticProductItem[] = [
  // 1. Core Development Hardware
  {
    id: "gen-prod-1",
    name: "Desktop 3D Printer",
    slug: "desktop-3d-printer",
    sku: "GEN-DEV-1-1",
    cost_price: 18000,
    price: 25200,
    compare_at_price: 31500,
    description: "Used for rapid prototyping of mechanical parts, enclosures and robot bodies via FDM printing.",
    short_description: "Used for rapid prototyping of mechanical parts, enclosures and robot bodies via FDM printing.",
    stock_quantity: 10,
    is_featured: true,
    status: "active",
    category: { name: "STEM & Robotics Kits", slug: "stem-kits" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/3d-printer-stem.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "FDM technology, standard build volume, PLA/ABS filament compatible, USB/SD card input." }]
  },
  {
    id: "gen-prod-2",
    name: "Arduino UNO",
    slug: "arduino-uno",
    sku: "GEN-ARD-1-2",
    cost_price: 200,
    price: 280,
    compare_at_price: 350,
    description: "Beginner-friendly microcontroller board for learning embedded programming and basic circuits.",
    short_description: "Beginner-friendly microcontroller board for learning embedded programming and basic circuits.",
    stock_quantity: 200,
    is_featured: true,
    status: "active",
    category: { name: "Arduino Ecosystem", slug: "arduino-products" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/arduino-uno-r3.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "ATmega328P MCU, 14 digital I/O pins, 6 analog inputs, 5V logic, USB programming." }]
  },
  {
    id: "gen-prod-3",
    name: "ESP32 Development Board",
    slug: "esp32-development-board",
    sku: "GEN-ESP-1-3",
    cost_price: 170,
    price: 238,
    compare_at_price: 298,
    description: "Wi-Fi/Bluetooth enabled microcontroller for IoT projects requiring wireless connectivity.",
    short_description: "Wi-Fi/Bluetooth enabled microcontroller for IoT projects requiring wireless connectivity.",
    stock_quantity: 100,
    is_featured: true,
    status: "active",
    category: { name: "ESP32 Ecosystem", slug: "esp32-products" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/esp32-development-board.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Dual-core 240MHz, Wi-Fi + BLE, 30+ GPIO pins, USB-to-serial programming." }]
  },
  {
    id: "gen-prod-4",
    name: "ESP32-C3 Development Board",
    slug: "esp32-c3-development-board",
    sku: "GEN-ESP-2-4",
    cost_price: 250,
    price: 350,
    compare_at_price: 438,
    description: "Compact, low-cost RISC-V based board for lightweight IoT applications.",
    short_description: "Compact, low-cost RISC-V based board for lightweight IoT applications.",
    stock_quantity: 100,
    is_featured: true,
    status: "active",
    category: { name: "ESP32 Ecosystem", slug: "esp32-products" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/esp32-development-board.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "RISC-V single-core, Wi-Fi + BLE 5.0, USB-C, small form factor." }]
  },

  // 2. Sensors & Modules
  {
    id: "gen-prod-5",
    name: "Push Button",
    slug: "push-button",
    sku: "GEN-PRT-1-5",
    cost_price: 20,
    price: 28,
    compare_at_price: 35,
    description: "Simple momentary switch used for user input in circuits.",
    short_description: "Simple momentary switch used for user input in circuits.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "Electronics & Accessories", slug: "electronics-components" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/push-button-module.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "4-pin tactile switch, 12x12mm, momentary contact." }]
  },
  {
    id: "gen-prod-6",
    name: "LDR (Light Sensor)",
    slug: "ldr-light-sensor",
    sku: "GEN-SEN-1-6",
    cost_price: 25,
    price: 35,
    compare_at_price: 44,
    description: "Detects ambient light intensity for light-based automation projects.",
    short_description: "Detects ambient light intensity for light-based automation projects.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "IoT & Smart Sensors", slug: "iot-sensors" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/ldr-light-sensor.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Photoresistor, resistance varies with light, 5mm package." }]
  },
  {
    id: "gen-prod-7",
    name: "Tilt Sensor",
    slug: "tilt-sensor",
    sku: "GEN-SEN-1-7",
    cost_price: 50,
    price: 70,
    compare_at_price: 88,
    description: "Detects orientation/tilt for motion or angle-based triggers.",
    short_description: "Detects orientation/tilt for motion or angle-based triggers.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "IoT & Smart Sensors", slug: "iot-sensors" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/tilt-sensor-module.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Ball-in-tube mercury-free switch, digital output." }]
  },
  {
    id: "gen-prod-8",
    name: "Sound Sensor",
    slug: "sound-sensor",
    sku: "GEN-SEN-1-8",
    cost_price: 40,
    price: 56,
    compare_at_price: 70,
    description: "Detects sound intensity/claps for sound-activated projects.",
    short_description: "Detects sound intensity/claps for sound-activated projects.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "IoT & Smart Sensors", slug: "iot-sensors" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/sound-detection-sensor.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Electret microphone with LM393 comparator, digital + analog output." }]
  },
  {
    id: "gen-prod-9",
    name: "Potentiometer",
    slug: "potentiometer",
    sku: "GEN-PRT-1-9",
    cost_price: 45,
    price: 63,
    compare_at_price: 79,
    description: "Variable resistor used for manual analog input control (volume, speed, etc.).",
    short_description: "Variable resistor used for manual analog input control (volume, speed, etc.).",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "Electronics & Accessories", slug: "electronics-components" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/potentiometer-10k.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "10K ohm rotary type, 3-pin, linear taper." }]
  },
  {
    id: "gen-prod-10",
    name: "IR Obstacle Sensor",
    slug: "ir-obstacle-sensor",
    sku: "GEN-SEN-1-10",
    cost_price: 25,
    price: 35,
    compare_at_price: 44,
    description: "Detects obstacles in front of robots using infrared reflection.",
    short_description: "Detects obstacles in front of robots using infrared reflection.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "IoT & Smart Sensors", slug: "iot-sensors" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/ir-obstacle-sensor.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "IR LED + phototransistor pair, adjustable sensitivity, digital output." }]
  },
  {
    id: "gen-prod-11",
    name: "Temperature Sensor (LM35)",
    slug: "temperature-sensor-lm35",
    sku: "GEN-SEN-1-11",
    cost_price: 40,
    price: 56,
    compare_at_price: 70,
    description: "Measures ambient temperature for monitoring/automation systems.",
    short_description: "Measures ambient temperature for monitoring/automation systems.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "IoT & Smart Sensors", slug: "iot-sensors" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/lm35-temperature-sensor.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Analog output, 10mV/°C, range -55°C to 150°C." }]
  },
  {
    id: "gen-prod-12",
    name: "Reed Switch Sensor",
    slug: "reed-switch-sensor",
    sku: "GEN-SEN-1-12",
    cost_price: 50,
    price: 70,
    compare_at_price: 88,
    description: "Detects presence of a magnetic field, used in door/proximity sensing.",
    short_description: "Detects presence of a magnetic field, used in door/proximity sensing.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "IoT & Smart Sensors", slug: "iot-sensors" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/reed-switch-sensor.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Magnetically operated switch, normally open contact." }]
  },
  {
    id: "gen-prod-13",
    name: "Ultrasonic Sensor",
    slug: "ultrasonic-sensor",
    sku: "GEN-SEN-1-13",
    cost_price: 65,
    price: 91,
    compare_at_price: 114,
    description: "Measures distance using sound waves; widely used in robotics for obstacle detection.",
    short_description: "Measures distance using sound waves; widely used in robotics for obstacle detection.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "IoT & Smart Sensors", slug: "iot-sensors" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/hc-sr04-ultrasonic.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "HC-SR04 type, 2cm-400cm range, trigger/echo pins." }]
  },
  {
    id: "gen-prod-14",
    name: "DHT11 Temperature & Humidity",
    slug: "dht11-temperature-humidity",
    sku: "GEN-SEN-1-14",
    cost_price: 60,
    price: 84,
    compare_at_price: 105,
    description: "Measures both temperature and humidity for environmental monitoring.",
    short_description: "Measures both temperature and humidity for environmental monitoring.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "IoT & Smart Sensors", slug: "iot-sensors" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/dht11-sensor.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Digital output, 0-50°C, 20-90% RH range." }]
  },
  {
    id: "gen-prod-15",
    name: "Flame Sensor",
    slug: "flame-sensor",
    sku: "GEN-SEN-1-15",
    cost_price: 25,
    price: 35,
    compare_at_price: 44,
    description: "Detects presence of fire/flame for fire-safety related projects.",
    short_description: "Detects presence of fire/flame for fire-safety related projects.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "IoT & Smart Sensors", slug: "iot-sensors" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/flame-detection-sensor.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "IR flame detection, 760-1100nm wavelength, digital/analog output." }]
  },
  {
    id: "gen-prod-16",
    name: "Water Level Sensor",
    slug: "water-level-sensor",
    sku: "GEN-SEN-1-16",
    cost_price: 20,
    price: 28,
    compare_at_price: 35,
    description: "Detects water level for tank monitoring and irrigation automation.",
    short_description: "Detects water level for tank monitoring and irrigation automation.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "IoT & Smart Sensors", slug: "iot-sensors" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/water-level-sensor.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Conductive trace strip, analog output." }]
  },
  {
    id: "gen-prod-17",
    name: "Touch Sensor",
    slug: "touch-sensor",
    sku: "GEN-SEN-1-17",
    cost_price: 10,
    price: 14,
    compare_at_price: 18,
    description: "Capacitive touch-based input switch for interactive projects.",
    short_description: "Capacitive touch-based input switch for interactive projects.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "IoT & Smart Sensors", slug: "iot-sensors" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/touch-sensor-ttp223.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "TTP223 module, digital output, touch-activated." }]
  },
  {
    id: "gen-prod-18",
    name: "I-Blink Module",
    slug: "i-blink-module",
    sku: "GEN-MOD-1-18",
    cost_price: 130,
    price: 182,
    compare_at_price: 228,
    description: "Specialized indicator/blink module used in signaling circuits.",
    short_description: "Specialized indicator/blink module used in signaling circuits.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "Electronics & Accessories", slug: "electronics-components" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/i-blink-module.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "LED blink driver module, standard voltage input." }]
  },
  {
    id: "gen-prod-19",
    name: "Relay Module",
    slug: "relay-module",
    sku: "GEN-MOD-1-19",
    cost_price: 30,
    price: 42,
    compare_at_price: 53,
    description: "Allows microcontrollers to switch high-power AC/DC loads safely.",
    short_description: "Allows microcontrollers to switch high-power AC/DC loads safely.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "Home & Lab Automation", slug: "home-automation" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/relay-module-5v.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "5V single-channel relay, optocoupler isolated, 10A contact rating." }]
  },
  {
    id: "gen-prod-20",
    name: "Servo Motor",
    slug: "servo-motor",
    sku: "GEN-MOT-1-20",
    cost_price: 65,
    price: 91,
    compare_at_price: 114,
    description: "Provides precise angular movement for robotic arms and mechanisms.",
    short_description: "Provides precise angular movement for robotic arms and mechanisms.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "Robotics & Kits", slug: "robotics-kits" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/sg90-servo-motor.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "SG90 micro servo, 180° rotation, PWM controlled." }]
  },
  {
    id: "gen-prod-21",
    name: "PIR Motion Sensor",
    slug: "pir-motion-sensor",
    sku: "GEN-SEN-1-21",
    cost_price: 60,
    price: 84,
    compare_at_price: 105,
    description: "Detects human/animal movement using infrared radiation.",
    short_description: "Detects human/animal movement using infrared radiation.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "IoT & Smart Sensors", slug: "iot-sensors" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/pir-motion-sensor.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "HC-SR501 type, adjustable delay & sensitivity, 3-7m range." }]
  },
  {
    id: "gen-prod-22",
    name: "Soil Moisture Sensor",
    slug: "soil-moisture-sensor",
    sku: "GEN-SEN-1-22",
    cost_price: 40,
    price: 56,
    compare_at_price: 70,
    description: "Measures soil moisture content for smart agriculture/irrigation projects.",
    short_description: "Measures soil moisture content for smart agriculture/irrigation projects.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "IoT & Smart Sensors", slug: "iot-sensors" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/soil-moisture-sensor.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Two-probe conductivity sensor, analog + digital output." }]
  },
  {
    id: "gen-prod-23",
    name: "Rain Sensor",
    slug: "rain-sensor",
    sku: "GEN-SEN-1-23",
    cost_price: 45,
    price: 63,
    compare_at_price: 79,
    description: "Detects rainfall/water droplets for weather-based automation.",
    short_description: "Detects rainfall/water droplets for weather-based automation.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "IoT & Smart Sensors", slug: "iot-sensors" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/rain-sensor-module.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Conductive PCB grid sensor, analog + digital output." }]
  },
  {
    id: "gen-prod-24",
    name: "MQ2 Gas Sensor",
    slug: "mq2-gas-sensor",
    sku: "GEN-SEN-1-24",
    cost_price: 90,
    price: 126,
    compare_at_price: 158,
    description: "Detects LPG, smoke and combustible gases for safety systems.",
    short_description: "Detects LPG, smoke and combustible gases for safety systems.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "IoT & Smart Sensors", slug: "iot-sensors" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/mq2-gas-sensor.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "MQ-2 semiconductor sensor, analog output, preheat required." }]
  },
  {
    id: "gen-prod-25",
    name: "Bluetooth Module (HC-05)",
    slug: "bluetooth-module-hc-05",
    sku: "GEN-COM-1-25",
    cost_price: 165,
    price: 231,
    compare_at_price: 289,
    description: "Enables wireless serial communication between devices via Bluetooth.",
    short_description: "Enables wireless serial communication between devices via Bluetooth.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "IoT & Smart Sensors", slug: "iot-sensors" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/hc05-bluetooth-module.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Bluetooth 2.0, master/slave mode, UART interface." }]
  },
  {
    id: "gen-prod-26",
    name: "Hall Effect Sensor",
    slug: "hall-effect-sensor",
    sku: "GEN-SEN-1-26",
    cost_price: 25,
    price: 35,
    compare_at_price: 44,
    description: "Detects magnetic field presence for speed/position sensing.",
    short_description: "Detects magnetic field presence for speed/position sensing.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "IoT & Smart Sensors", slug: "iot-sensors" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/hall-effect-sensor.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Digital output, activates near magnetic field." }]
  },
  {
    id: "gen-prod-27",
    name: "Vibration Sensor",
    slug: "vibration-sensor",
    sku: "GEN-SEN-1-27",
    cost_price: 30,
    price: 42,
    compare_at_price: 53,
    description: "Detects mechanical vibration/shock for security or monitoring projects.",
    short_description: "Detects mechanical vibration/shock for security or monitoring projects.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "IoT & Smart Sensors", slug: "iot-sensors" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/vibration-sensor-sw420.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "SW-420 module, digital output, adjustable sensitivity." }]
  },
  {
    id: "gen-prod-28",
    name: "IR Line Tracking Sensor",
    slug: "ir-line-tracking-sensor",
    sku: "GEN-SEN-1-28",
    cost_price: 24,
    price: 34,
    compare_at_price: 43,
    description: "Detects line contrast for line-following robots.",
    short_description: "Detects line contrast for line-following robots.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "Robotics & Kits", slug: "robotics-kits" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/ir-line-tracking-sensor.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "IR reflective sensor, digital output, adjustable threshold." }]
  },
  {
    id: "gen-prod-29",
    name: "RFID Module",
    slug: "rfid-module",
    sku: "GEN-COM-1-29",
    cost_price: 75,
    price: 105,
    compare_at_price: 131,
    description: "Enables contactless identification/access systems using RFID tags.",
    short_description: "Enables contactless identification/access systems using RFID tags.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "IoT & Smart Sensors", slug: "iot-sensors" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/rfid-rc522-kit.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "RC522 13.56MHz reader/writer, SPI interface, includes tag & card." }]
  },
  {
    id: "gen-prod-30",
    name: "MQ135 Air Quality Sensor",
    slug: "mq135-air-quality-sensor",
    sku: "GEN-SEN-1-30",
    cost_price: 90,
    price: 126,
    compare_at_price: 158,
    description: "Detects air quality by sensing gases like ammonia, CO2, and smoke.",
    short_description: "Detects air quality by sensing gases like ammonia, CO2, and smoke.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "IoT & Smart Sensors", slug: "iot-sensors" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/mq135-air-quality-sensor.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "MQ-135 semiconductor sensor, analog output." }]
  },
  {
    id: "gen-prod-31",
    name: "BH1750 Light Intensity Sensor",
    slug: "bh1750-light-intensity-sensor",
    sku: "GEN-SEN-1-31",
    cost_price: 95,
    price: 133,
    compare_at_price: 166,
    description: "Provides precise digital ambient light intensity measurement in lux.",
    short_description: "Provides precise digital ambient light intensity measurement in lux.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "IoT & Smart Sensors", slug: "iot-sensors" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/bh1750-light-sensor.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "I2C digital output, 1-65535 lux range." }]
  },
  {
    id: "gen-prod-32",
    name: "BMP180 Barometric Pressure Sensor",
    slug: "bmp180-barometric-pressure-sensor",
    sku: "GEN-SEN-1-32",
    cost_price: 38,
    price: 53,
    compare_at_price: 66,
    description: "Measures atmospheric pressure and altitude for weather stations.",
    short_description: "Measures atmospheric pressure and altitude for weather stations.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "IoT & Smart Sensors", slug: "iot-sensors" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/bmp180-pressure-sensor.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "I2C interface, 300-1100hPa range, includes temperature reading." }]
  },
  {
    id: "gen-prod-33",
    name: "OLED Display Module",
    slug: "oled-display-module",
    sku: "GEN-DIS-1-33",
    cost_price: 130,
    price: 182,
    compare_at_price: 228,
    description: "Compact display for showing sensor data/text in embedded projects.",
    short_description: "Compact display for showing sensor data/text in embedded projects.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "Electronics & Accessories", slug: "electronics-components" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/oled-display-096.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "0.96\" I2C OLED, 128x64 resolution, monochrome." }]
  },
  {
    id: "gen-prod-34",
    name: "Motion Sensor (RCWL-0516)",
    slug: "motion-sensor-rcwl-0516",
    sku: "GEN-SEN-1-34",
    cost_price: 60,
    price: 84,
    compare_at_price: 105,
    description: "General-purpose motion detection module for automation projects.",
    short_description: "General-purpose motion detection module for automation projects.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "IoT & Smart Sensors", slug: "iot-sensors" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/rcwl0516-radar-sensor.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Digital output motion detector, adjustable sensitivity." }]
  },
  {
    id: "gen-prod-35",
    name: "Amplifier Module",
    slug: "amplifier-module",
    sku: "GEN-MOD-1-35",
    cost_price: 180,
    price: 252,
    compare_at_price: 315,
    description: "Amplifies audio signals for speaker output in sound-based projects.",
    short_description: "Amplifies audio signals for speaker output in sound-based projects.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "Electronics & Accessories", slug: "electronics-components" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/pam8403-amplifier.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Class-D audio amplifier module, standard voltage input." }]
  },

  // 3. Electronics Components & Accessories
  {
    id: "gen-prod-36",
    name: "LED Assortment Kits",
    slug: "led-assortment-kits",
    sku: "GEN-PRT-1-36",
    cost_price: 2,
    price: 3,
    compare_at_price: 4,
    description: "Basic indicator LEDs for circuit prototyping and signaling.",
    short_description: "Basic indicator LEDs for circuit prototyping and signaling.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "Electronics & Accessories", slug: "electronics-components" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/rgb-led-5mm.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Assorted colors (Red/Green/Blue/Yellow), 5mm, standard forward voltage." }]
  },
  {
    id: "gen-prod-37",
    name: "PCB (0 PCB)",
    slug: "pcb-0-pcb",
    sku: "GEN-PRT-1-37",
    cost_price: 250,
    price: 350,
    compare_at_price: 438,
    description: "Perforated prototyping board for soldering and permanent circuit builds.",
    short_description: "Perforated prototyping board for soldering and permanent circuit builds.",
    stock_quantity: 500,
    is_featured: false,
    status: "active",
    category: { name: "Electronics & Accessories", slug: "electronics-components" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/dot-matrix-pcb.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "General-purpose zero PCB, standard hole spacing." }]
  },
  {
    id: "gen-prod-38",
    name: "Resistor Kits",
    slug: "resistor-kits",
    sku: "GEN-PRT-1-38",
    cost_price: 250,
    price: 350,
    compare_at_price: 438,
    description: "Assorted resistors used for current-limiting and voltage division in circuits.",
    short_description: "Assorted resistors used for current-limiting and voltage division in circuits.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "Electronics & Accessories", slug: "electronics-components" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/resistor-kit-pack.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Assorted values (typically 1Ω-1MΩ), 1/4W carbon film." }]
  },
  {
    id: "gen-prod-39",
    name: "Breadboards",
    slug: "breadboards",
    sku: "GEN-PRT-1-39",
    cost_price: 250,
    price: 350,
    compare_at_price: 438,
    description: "Solderless prototyping boards for temporary circuit assembly.",
    short_description: "Solderless prototyping boards for temporary circuit assembly.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "Electronics & Accessories", slug: "electronics-components" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/mb102-breadboard.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "830-point standard size breadboard." }]
  },
  {
    id: "gen-prod-40",
    name: "Jumper Wire Sets",
    slug: "jumper-wire-sets",
    sku: "GEN-PRT-1-40",
    cost_price: 40,
    price: 56,
    compare_at_price: 70,
    description: "Connecting wires for breadboard and module interconnections.",
    short_description: "Connecting wires for breadboard and module interconnections.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "Electronics & Accessories", slug: "electronics-components" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/jumper-wire-male-male.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Male-Male/Male-Female/Female-Female assorted sets." }]
  },
  {
    id: "gen-prod-41",
    name: "Switches",
    slug: "switches",
    sku: "GEN-PRT-1-41",
    cost_price: 2,
    price: 3,
    compare_at_price: 4,
    description: "General-purpose on/off switches for power control in circuits.",
    short_description: "General-purpose on/off switches for power control in circuits.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "Electronics & Accessories", slug: "electronics-components" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/push-button-module.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "SPST toggle/slide switch, standard rating." }]
  },
  {
    id: "gen-prod-42",
    name: "Battery Holders",
    slug: "battery-holders",
    sku: "GEN-PWR-1-42",
    cost_price: 20,
    price: 28,
    compare_at_price: 35,
    description: "Holds batteries securely and provides connection points for power supply.",
    short_description: "Holds batteries securely and provides connection points for power supply.",
    stock_quantity: 250,
    is_featured: false,
    status: "active",
    category: { name: "Electronics & Accessories", slug: "electronics-components" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/battery-holder-18650.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "AA/9V compatible holder with lead wires." }]
  },
  {
    id: "gen-prod-43",
    name: "Rechargeable Batteries",
    slug: "rechargeable-batteries",
    sku: "GEN-PWR-1-43",
    cost_price: 60,
    price: 84,
    compare_at_price: 105,
    description: "Reusable power source for portable projects and robots.",
    short_description: "Reusable power source for portable projects and robots.",
    stock_quantity: 250,
    is_featured: false,
    status: "active",
    category: { name: "Electronics & Accessories", slug: "electronics-components" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/rechargeable-18650-battery.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "NiMH/Li-ion rechargeable cells, standard capacity." }]
  },
  {
    id: "gen-prod-44",
    name: "Battery Chargers",
    slug: "battery-chargers",
    sku: "GEN-PWR-1-44",
    cost_price: 60,
    price: 84,
    compare_at_price: 105,
    description: "Used to recharge rechargeable batteries used in lab projects.",
    short_description: "Used to recharge rechargeable batteries used in lab projects.",
    stock_quantity: 100,
    is_featured: false,
    status: "active",
    category: { name: "Electronics & Accessories", slug: "electronics-components" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/lipo-battery-b3-charger.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Multi-slot charger compatible with AA/Li-ion cells." }]
  },
  {
    id: "gen-prod-45",
    name: "USB Programming Cables",
    slug: "usb-programming-cables",
    sku: "GEN-PRT-1-45",
    cost_price: 20,
    price: 28,
    compare_at_price: 35,
    description: "Used to connect and program microcontroller boards via USB.",
    short_description: "Used to connect and program microcontroller boards via USB.",
    stock_quantity: 50,
    is_featured: false,
    status: "active",
    category: { name: "Electronics & Accessories", slug: "electronics-components" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/usb-programming-cable.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "USB-A to Micro-USB/Type-C, standard data cable." }]
  },
  {
    id: "gen-prod-46",
    name: "Power Supply Modules",
    slug: "power-supply-modules",
    sku: "GEN-PWR-1-46",
    cost_price: 250,
    price: 350,
    compare_at_price: 438,
    description: "Regulates voltage for powering breadboard circuits.",
    short_description: "Regulates voltage for powering breadboard circuits.",
    stock_quantity: 150,
    is_featured: false,
    status: "active",
    category: { name: "Electronics & Accessories", slug: "electronics-components" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/extension-board.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Breadboard power supply module, 3.3V/5V dual output." }]
  },

  // 4. Fabrication & Assembly Tools
  {
    id: "gen-prod-47",
    name: "Heat Gun",
    slug: "heat-gun",
    sku: "GEN-TOL-1-47",
    cost_price: 250,
    price: 350,
    compare_at_price: 438,
    description: "Used for heat-shrink tubing and desoldering applications.",
    short_description: "Used for heat-shrink tubing and desoldering applications.",
    stock_quantity: 10,
    is_featured: false,
    status: "active",
    category: { name: "STEM & Robotics Kits", slug: "stem-kits" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/hot-glue-gun.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Dual temperature settings, standard household voltage." }]
  },
  {
    id: "gen-prod-48",
    name: "Glue Gun",
    slug: "glue-gun",
    sku: "GEN-TOL-1-48",
    cost_price: 250,
    price: 350,
    compare_at_price: 438,
    description: "Used for quick mechanical bonding in prototyping and enclosures.",
    short_description: "Used for quick mechanical bonding in prototyping and enclosures.",
    stock_quantity: 25,
    is_featured: false,
    status: "active",
    category: { name: "STEM & Robotics Kits", slug: "stem-kits" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/hot-glue-gun.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Hot melt glue gun, standard glue stick size." }]
  },
  {
    id: "gen-prod-49",
    name: "Soldering Iron Kit",
    slug: "soldering-iron-kit",
    sku: "GEN-TOL-1-49",
    cost_price: 250,
    price: 350,
    compare_at_price: 438,
    description: "Essential tool for soldering electronic components onto PCBs.",
    short_description: "Essential tool for soldering electronic components onto PCBs.",
    stock_quantity: 50,
    is_featured: false,
    status: "active",
    category: { name: "STEM & Robotics Kits", slug: "stem-kits" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/soldering-iron-kit.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "30-60W adjustable iron with stand, solder wire & accessories." }]
  },
  {
    id: "gen-prod-50",
    name: "Screwdriver Kit",
    slug: "screwdriver-kit",
    sku: "GEN-TOL-1-50",
    cost_price: 250,
    price: 350,
    compare_at_price: 438,
    description: "Used for assembling/disassembling mechanical and electronic enclosures.",
    short_description: "Used for assembling/disassembling mechanical and electronic enclosures.",
    stock_quantity: 50,
    is_featured: false,
    status: "active",
    category: { name: "STEM & Robotics Kits", slug: "stem-kits" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/precision-screwdriver-kit.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Precision multi-bit screwdriver set." }]
  },
  {
    id: "gen-prod-51",
    name: "Wire Stripper",
    slug: "wire-stripper",
    sku: "GEN-TOL-1-51",
    cost_price: 250,
    price: 350,
    compare_at_price: 438,
    description: "Used to strip insulation from wires for connections.",
    short_description: "Used to strip insulation from wires for connections.",
    stock_quantity: 50,
    is_featured: false,
    status: "active",
    category: { name: "STEM & Robotics Kits", slug: "stem-kits" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/automatic-wire-stripper.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Adjustable multi-gauge wire stripper/cutter." }]
  },
  {
    id: "gen-prod-52",
    name: "Cutting Plier",
    slug: "cutting-plier",
    sku: "GEN-TOL-1-52",
    cost_price: 250,
    price: 350,
    compare_at_price: 438,
    description: "Used for cutting wires and component leads.",
    short_description: "Used for cutting wires and component leads.",
    stock_quantity: 50,
    is_featured: false,
    status: "active",
    category: { name: "STEM & Robotics Kits", slug: "stem-kits" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/long-nose-plier.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Standard diagonal cutting plier." }]
  },
  {
    id: "gen-prod-53",
    name: "Long Nose Plier",
    slug: "long-nose-plier",
    sku: "GEN-TOL-1-53",
    cost_price: 250,
    price: 350,
    compare_at_price: 438,
    description: "Used for gripping and bending wires in tight spaces.",
    short_description: "Used for gripping and bending wires in tight spaces.",
    stock_quantity: 50,
    is_featured: false,
    status: "active",
    category: { name: "STEM & Robotics Kits", slug: "stem-kits" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/long-nose-plier.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Standard long-nose (needle-nose) plier." }]
  },
  {
    id: "gen-prod-54",
    name: "Digital Multimeter",
    slug: "digital-multimeter",
    sku: "GEN-TOL-1-54",
    cost_price: 250,
    price: 350,
    compare_at_price: 438,
    description: "Used to measure voltage, current, resistance and continuity in circuits.",
    short_description: "Used to measure voltage, current, resistance and continuity in circuits.",
    stock_quantity: 25,
    is_featured: false,
    status: "active",
    category: { name: "STEM & Robotics Kits", slug: "stem-kits" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/dt830d-digital-multimeter.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Digital display, DC/AC voltage, current & resistance measurement." }]
  },
  {
    id: "gen-prod-55",
    name: "Helping Hand Tool",
    slug: "helping-hand-tool",
    sku: "GEN-TOL-1-55",
    cost_price: 250,
    price: 350,
    compare_at_price: 438,
    description: "Holds PCBs/components steady during soldering work.",
    short_description: "Holds PCBs/components steady during soldering work.",
    stock_quantity: 50,
    is_featured: false,
    status: "active",
    category: { name: "STEM & Robotics Kits", slug: "stem-kits" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/soldering-iron-kit.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Adjustable arms with alligator clips and magnifier." }]
  },
  {
    id: "gen-prod-56",
    name: "Electrical Tape",
    slug: "electrical-tape",
    sku: "GEN-TOL-1-56",
    cost_price: 250,
    price: 350,
    compare_at_price: 438,
    description: "Used for insulating wire connections and joints.",
    short_description: "Used for insulating wire connections and joints.",
    stock_quantity: 50,
    is_featured: false,
    status: "active",
    category: { name: "STEM & Robotics Kits", slug: "stem-kits" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/insulation-tape.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "PVC insulation tape, standard roll." }]
  },
  {
    id: "gen-prod-57",
    name: "Double-Sided Tape",
    slug: "double-sided-tape",
    sku: "GEN-TOL-1-57",
    cost_price: 250,
    price: 350,
    compare_at_price: 438,
    description: "Used for mounting components/modules onto surfaces.",
    short_description: "Used for mounting components/modules onto surfaces.",
    stock_quantity: 50,
    is_featured: false,
    status: "active",
    category: { name: "STEM & Robotics Kits", slug: "stem-kits" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/insulation-tape.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Adhesive on both sides, standard roll." }]
  },
  {
    id: "gen-prod-58",
    name: "Safety Goggles",
    slug: "safety-goggles",
    sku: "GEN-TOL-1-58",
    cost_price: 250,
    price: 350,
    compare_at_price: 438,
    description: "Protects eyes during soldering, cutting and fabrication work.",
    short_description: "Protects eyes during soldering, cutting and fabrication work.",
    stock_quantity: 50,
    is_featured: false,
    status: "active",
    category: { name: "STEM & Robotics Kits", slug: "stem-kits" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/plastic-project-box.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Impact-resistant clear lens, adjustable strap." }]
  },

  // 5. Display Projects
  {
    id: "gen-prod-59",
    name: "Automatic Grass Cutter",
    slug: "automatic-grass-cutter",
    sku: "GEN-ROB-1-59",
    cost_price: 7500,
    price: 10500,
    compare_at_price: 13125,
    description: "A demo robot that autonomously trims grass using rotating blades and obstacle sensing.",
    short_description: "A demo robot that autonomously trims grass using rotating blades and obstacle sensing.",
    stock_quantity: 5,
    is_featured: true,
    status: "active",
    category: { name: "Robotics & Kits", slug: "robotics-kits" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/car-kit-2-chassis-boards.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Motorized cutting blade, DC motor drive, obstacle avoidance sensors." }]
  },
  {
    id: "gen-prod-60",
    name: "Smart Pesticide Sprayer",
    slug: "smart-pesticide-sprayer",
    sku: "GEN-ROB-1-60",
    cost_price: 8600,
    price: 12040,
    compare_at_price: 15050,
    description: "A demo agricultural robot that sprays pesticide automatically over crops.",
    short_description: "A demo agricultural robot that sprays pesticide automatically over crops.",
    stock_quantity: 5,
    is_featured: true,
    status: "active",
    category: { name: "Robotics & Kits", slug: "robotics-kits" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/car-kit-2-chassis-boards.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Pump-based sprayer mechanism, motorized chassis, tank reservoir." }]
  },
  {
    id: "gen-prod-61",
    name: "Voice Control Robot",
    slug: "voice-control-robot",
    sku: "GEN-ROB-1-61",
    cost_price: 6000,
    price: 8400,
    compare_at_price: 10500,
    description: "A robot that moves and performs actions based on voice commands.",
    short_description: "A robot that moves and performs actions based on voice commands.",
    stock_quantity: 5,
    is_featured: true,
    status: "active",
    category: { name: "Robotics & Kits", slug: "robotics-kits" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/otto-bot-kit.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Voice recognition module, motor driver, wireless/Bluetooth control." }]
  },
  {
    id: "gen-prod-62",
    name: "Humanoid Fire Fighter",
    slug: "humanoid-fire-fighter",
    sku: "GEN-ROB-1-62",
    cost_price: 5500,
    price: 7700,
    compare_at_price: 9625,
    description: "A humanoid demo robot designed to simulate firefighting actions.",
    short_description: "A humanoid demo robot designed to simulate firefighting actions.",
    stock_quantity: 5,
    is_featured: true,
    status: "active",
    category: { name: "Robotics & Kits", slug: "robotics-kits" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/otto-bot-kit.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Servo-driven humanoid frame, flame sensor integration." }]
  },
  {
    id: "gen-prod-63",
    name: "Robotic Arms",
    slug: "robotic-arms",
    sku: "GEN-ROB-1-63",
    cost_price: 2400,
    price: 3360,
    compare_at_price: 4200,
    description: "Demonstration robotic arms used to teach pick-and-place and articulation concepts.",
    short_description: "Demonstration robotic arms used to teach pick-and-place and articulation concepts.",
    stock_quantity: 20,
    is_featured: true,
    status: "active",
    category: { name: "Robotics & Kits", slug: "robotics-kits" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/robotic-arm-kit.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Multi-servo articulated arm, gripper end-effector." }]
  },
  {
    id: "gen-prod-64",
    name: "6 Wheel Kit",
    slug: "6-wheel-kit",
    sku: "GEN-ROB-1-64",
    cost_price: 1200,
    price: 1680,
    compare_at_price: 2100,
    description: "A rugged 6-wheel drive chassis kit for building all-terrain robots.",
    short_description: "A rugged 6-wheel drive chassis kit for building all-terrain robots.",
    stock_quantity: 10,
    is_featured: true,
    status: "active",
    category: { name: "Robotics & Kits", slug: "robotics-kits" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/6wheel-robot-kit.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "6-wheel drive chassis with DC motors, metal/plastic frame." }]
  },
  {
    id: "gen-prod-65",
    name: "Spider Robot",
    slug: "spider-robot",
    sku: "GEN-ROB-1-65",
    cost_price: 1850,
    price: 2590,
    compare_at_price: 3237.5,
    description: "A multi-legged walking robot used to demonstrate legged locomotion.",
    short_description: "A multi-legged walking robot used to demonstrate legged locomotion.",
    stock_quantity: 10,
    is_featured: true,
    status: "active",
    category: { name: "Robotics & Kits", slug: "robotics-kits" },
    brand: { name: "GenBots", slug: "genbots" },
    images: [{ url: "/products/spider-robot-kit.jpg", is_primary: true }],
    specifications: [{ key: "Specification", value: "Multi-servo leg mechanism, spider-like walking gait." }]
  },
];

export const productsData = INNOVATION_LAB_65_PRODUCTS;
